# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-destruct
spec:
  replicas: 1
  template:
    spec:
      repository: nikimanoledaki/sustainability-journey-with-gitops
      labels:
      - equinix-rhel
      - self-destruct
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: manual-destruct
spec:
  replicas: 1
  template:
    spec:
      ephemeral: false
      repository: nikimanoledaki/sustainability-journey-with-gitops
      labels:
      - equinix-rhel
      - manual-destruct
