name: test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: test
    runs-on: [self-hosted, equinix-rhel, manual-destruct]
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f https://raw.githubusercontent.com/nikimanoledaki/date-setter/main/build/default-deployment.yaml